exp_name: B005_purecrm_ess_sample1_lr1
data_dir: /scratch/srasp/preprocessed_data/
train_fn: purecrm_ess_train_sample1_shuffle
valid_fn: purecrm_ess_valid_sample1
hidden_layers: [512]
log_dir: ../logs/
lr: 1e-4
lr_step: 3
epochs: 20