exp_name: B008_purecrm_ess_sample1_bs512
data_dir: /scratch/srasp/preprocessed_data/
train_fn: purecrm_ess_train_sample1_shuffle
valid_fn: purecrm_ess_valid_sample1
hidden_layers: [512]
log_dir: ../logs/
batch_size: 512
